#include "../lv_conf.h"

#undef LV_USE_PROFILER
#define LV_USE_PROFILER 0

#undef LV_PROFILER_BEGIN
#undef LV_PROFILER_END
#undef LV_PROFILER_BEGIN_TAG
#undef LV_PROFILER_END_TAG

#undef LV_USE_DRAW_DMA2D
#define LV_USE_DRAW_DMA2D 0
